version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile
    ports:
      - "8000:8000"  # Port mapping for FastAPI

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"  # Port mapping for Vue.js development server
